routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');


Route::resource('user', 'UserController');
Route::get('/user', 'UserController@search')->name('user.search');

Route::resource('post', 'PostController');
Route::get('/post', 'PostController@search')->name('post.search');

Route::resource('skyobject', 'SkyObjectController');
Route::get('/skyobject', 'SkyObjectController@search')->name('skyobject.search');

Route::resource('spacecraft', 'SpacecraftController');
Route::get('/spacecraft', 'SpacecraftController@search')->name('spacecraft.search');

Route::resource('occurrence', 'OccurrenceController');
Route::get('/occurrence', 'OccurrenceController@search')->name('occurrence.search');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public $table = 'post';
    protected $fillable = [
        'title', 'bodypost', 'created_at'
    ];
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;
use App\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function index()
    {
        $post = \App\Post::paginate();
        return view('post.index',compact('post'));
    }

    public function create()
    {
        $post = Post::all();
        return view('post.create', ['post'=>$post]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'title'=>'required|min:5',
            'bodypost'=>'required|min:5',
            'picture'=>'required|image|mimes:jpg,jpeg,png,bmp',
        ]);

        $file = $request->file('picture');
        $path = $file->store('picture', 'public');

        Post::create([
            'title'=>$request->title,
            'bodypost'=>$request->bodypost,
            'picture'=>$path,
        ]);

        return redirect()->route('post.create')->with('status', 'Post was Successfully Created');
    }

    public function show($id)
    {
        $post = Post::findOrFail($id);
        return view('post.show',['post'=>$post]);
    }

    public function edit($id)
    {
        $post = Post::findOrFail($id);
        return view('post.edit',['post'=>$post]);
    }

    public function update(Request $request, $id)
    {
        $update_post = Post::findOrFail($id);
        $request->validate([
            'title'=>'required|min:5',
            'bodypost'=>'required|min:5',
            'picture'=>'required|image|mimes:jpg,jpeg,png,bmp',
        ]);

        $update_post->update([
            'title'=>$request->title,
            'bodypost'=>$request->bodypost,
            'picture'=>$request->avatar,
        ]);

        if($request->file('picture')) 
        {
            if ($update_post->picture && file_exists(storage_path('app/public/'.$update_post->picture))) 
            {
                Storage::delete('public/'.$update_post->picture);
            }

            $file = $request->file('picture')->store('picture', 'public');
            $update_post->picture = $file;
        }

        $update_post->save();
        return redirect()->route('post.edit',['post'=>$update_post])->with('status', 'Post was Updated Successfully');
    }

    public function destroy($id)
    {
        $post = Post::findOrFail($id);
        if ($post->picture && file_exists(storage_path('app/public/'.$post->picture))) 
        {
            Storage::delete('public/'.$post->picture);
        }
        $post->delete();
        return redirect()->back()->with('status', 'Post was Successfully deleted');
    }

    public function search(Request $request)
    {
       $cari = $request->get('search');
       $post = Post::where('title', 'LIKE', '%'.$cari.'%')->orderBy('created_at', 'DESC')->paginate(5);
       return view('post.index', ['post'=>$post]);
    }
}

resources/views/post/create.blade.php
@extends('templates.home')
@section('title')
    Create Post
@endsection
@section('content')
    <div class="container" >
        <h3>Create Post</h3>
        <hr>
        @if (session('status'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{ session('status') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
        @endif
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5> Create a New Post</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('post.store') }}" class="form-group" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="title">Title</label>
                            </div>
                            <div class="col-md-8">
                                <input value="{{ old('title') }}" type="text" class="form-control {{$errors->first('title') ? "is-invalid": ""}}" name="title" id="title">
                                    <div class="invalid-feedback">
                                        {{$errors->first('title')}}
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="bodypost">Content</label>
                            </div>
                            <div class="col-md-8">
                                <textarea class="form-control {{$errors->first('bodypost')? "is-invalid": ""}}" name="bodypost" id="bodypost" cols="30" rows="5"></textarea>
                                <div class="invalid-feedback">
                                    {{$errors->first('bodypost')}}
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                Picture
                            </div>
                            <div class="col-md-8">
                                <div class="custom-file">
                                    <label for="picture" class="custom-file-label">Picture</label>
                                        <input type="file" class="custom-file-input {{$errors->first('picture') ? "is-invalid": ""}}" name="picture" id="picture">
                                            <div class="invalid-feedback">
                                                {{$errors->first('picture')}}
                                            </div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary">Create</button>
                            </div>
                        </div>
                    </form>   
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/post/edit.blade.php
@extends('templates.home')
@section('title')
    Edit Post
@endsection
@section('content')
    <div class="container" >
        <h3>Edit Post</h3>
        <hr>
        @if (session('status'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{ session('status') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
        @endif
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5>Edit Post</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('post.update',$post['id']) }}" method="POST" class="form-group" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-3">
                                <label for="title" class="text-primary">Title</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control {{$errors->first('title') ? "is-invalid": ""}}" name="title" id="title" 
                                value="{{ old('title') ? old('title') : $post['title'] }}">
                                    <div class="invalid-feedback">
                                        {{$errors->first('title')}}
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="bodypost" class="text-primary">Content</label>
                            </div>
                            <div class="col-md-8">
                                <textarea class="form-control {{$errors->first('bodypost') ? "is-invalid": ""}}" name="bodypost" id="bodypost" 
                                    value="{{ old('bodypost') ? old('bodypost') : $post['bodypost'] }}"></textarea>
                                    <div class="invalid-feedback">
                                        {{$errors->first('bodypost')}}
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                Picture
                            </div>
                        <div class="col-md-8">
                                <img src="{{asset('storage/'.$post['picture'])}}" class="img-thumbnail" height="150px" width="150px" alt="">
                                    <div class="custom-file">
                                        <label for="picture" class="custom-file-label">Picture</label>
                                            <input type="file" class="custom-file-input {{$errors->first('picture') ? "is-invalid": ""}}" name="picture" id="picture">
                                                <div class="invalid-feedback">
                                                    {{$errors->first('picture')}}
                                                </div>
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary">Update</button>
                            </div>
                        </div>
                    </form>   
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/post/index.blade.php
@extends('templates.home')
@section('title')
 	Post
@endsection
@section('css')
<style>
	body{
		padding-top: 30px;
	}
	th, td {
		padding: 10px;
		text-align: center;
	}
	td a{
		margin: 3px;
		align-bodypost: center;
		color: white;
	}
	td a:hover{
		text-decoration: none;
	}
	td button{
		margin-top: 5px;
		cursor: pointer;
	 }
</style>
@endsection
@section('content')
	<div class="container">
		<h3> Post</h3>
		<hr>
		@if (session('status'))
		<div class="alert alert-info alert-dismissible fade show" role="alert">
			<strong> {{ session('status') }} </strong>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		@endif
		<div class="row">
			<div class="col-md-2">
				<a href=" {{ route('post.create') }} " class="btn btn-outline-primary">
					<span data-feather="plus-square"></span> Add post<span class="sr-only">(current)</span>
				</a>
			</div>
			<div class="col-md-8">
				<form action=" {{ route('post.search') }} " method="get">
					<div class="input-group custom-search-form">
						<input type="text" name="search" placeholder="Filter by Title" class="form-control">
						<span class="input-group-btn">&nbsp;
							<button class="btn btn-outline-dark" type="submit">Filter</button>
						</span>
					</div>
				</form>
			</div>
		</div>
		<br>
		<div class="tabel-responsive">
			<table class="table table-hover">
				<thead>
					<tr class="table-primary">
						<th scope="col">ID</th>
						<th scope="col">Title</th>
						<th scope="col">Picture</th>
						<th scope="col">Action</th>
					</tr>
				</thead>
				<tbody>
				@foreach ($post as $posts)
					<tr>
						<th>{{ $posts['id'] }}</th>
                        <th>{{ $posts['title'] }}</th>
						<td>
							<img src="{{asset('storage/'.$posts['picture'])}}" class="img-thumbnail" width="80px" alt="N/A">
						</td>
						<td>
							
							<a href="{{ route('post.show', ['id'=>$posts['id']]) }}" class="btn-sm btn-primary">
								<span data-feather="eye"></span> Detail<span class="sr-only">(current)</span>
							</a>
							<a href="{{ route('post.edit', ['id'=>$posts['id']]) }}" class="btn-sm btn-success">
								<span data-feather="edit"></span> Edit<span class="sr-only">(current)</span>
							</a>
							<form class="d-inline" onsubmit="return confirm('Permanently Delete post?')" action="{{ route('post.destroy', ['id'=>$posts['id']]) }}" method="POST">
								@csrf
								@method('DELETE')
								<button type="submit" class="btn-sm btn-danger" value="Delete" name="submit">
									<span data-feather="trash"></span> Delete<span class="sr-only">(current)</span>
								</button>
							</form>
						</td>
					</tr>
				@endforeach
				</tbody>
			</table>
		</div>
		<div class="pagination justify-bodypost-center"> {{ $post->links() }} </div>
	</div>
@endsection

resources/views/post/show.blade.php
@extends('templates.home')
@section('title')
    Post
@endsection
@section('content')
    <h1>{{ $post['title'] }}</h1>
    <hr>
    <br>
    <div class="card bg-white border-info" style="max-width: 70%; margin: auto; min-height: 400px;">

			<div class="card mb-4">
                <div class="card-body">
                    <img src="{{asset('storage/'.$post['picture'])}}" class="img-thumbnail" width="150px" alt="N/A">
                    <p class="card-text"> {{$post['bodypost']}} </p>
                </div>
                <div class="card-footer text-muted">
                    Posted on {{ $post['created_at'] }}
                </div>
            </div>
    </div>
@endsection