routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');


Route::resource('user', 'UserController');
Route::get('/user', 'UserController@search')->name('user.search');

Route::resource('post', 'PostController');
Route::get('/post', 'PostController@search')->name('post.search');

Route::resource('skyobject', 'SkyObjectController');
Route::get('/skyobject', 'SkyObjectController@search')->name('skyobject.search');

Route::resource('spacecraft', 'SpacecraftController');
Route::get('/spacecraft', 'SpacecraftController@search')->name('spacecraft.search');

Route::resource('occurrence', 'OccurrenceController');
Route::get('/occurrence', 'OccurrenceController@search')->name('occurrence.search');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/SkyObject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SkyObject extends Model
{
    public $table = 'skyobject';
    protected $fillable = [
        'name', 'type', 'distance',
    ];
}

app/Http/Controllers/SkyObjectController.php
<?php

namespace App\Http\Controllers;
use App\SkyObject;
use Illuminate\Http\Request;

class SkyObjectController extends Controller
{
    public function index()
    {
        $skyobject = \App\SkyObject::paginate();
        return view('skyobject.index',compact('skyobject'));
    }

    public function create()
    {
        $skyobject = SkyObject::all();
        return view('skyobject.create', ['skyobject'=>$skyobject]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'type'=>'required',
            'distance'=>'required',
            'picture'=>'required|image|mimes:jpg,jpeg,png,bmp',
        ]);

        $file = $request->file('picture');
        $path = $file->store('picture', 'public');

        SkyObject::create([
            'name'=>$request->name,
            'type'=>$request->type,
            'distance'=>$request->distance,
            'picture'=>$path,
        ]);

        return redirect()->route('skyobject.create')->with('status', 'Sky Object Data was Successfully Created');
    }

    public function show($id)
    {
        $skyobject = SkyObject::findOrFail($id);
        return view('skyobject.show',['skyobject'=>$skyobject]);
    }

    public function edit($id)
    {
        $skyobject = SkyObject::findOrFail($id);
        return view('skyobject.edit',['skyobject'=>$skyobject]);
    }

    public function update(Request $request, $id)
    {
        $update_spacecraft = SkyObject::findOrFail($id);
        $request->validate([
            'name'=>'required',
            'type'=>'required',
            'distance'=>'required',
            'picture'=>'required|image|mimes:jpg,jpeg,png,bmp',
        ]);

        $update_spacecraft->update([
            'name'=>$request->name,
            'type'=>$request->type,
            'distance'=>$request->distance,
            'picture'=>$request->picture,
        ]);

        if($request->file('picture')) 
        {
            if ($update_spacecraft->picture && file_exists(storage_path('app/public/'.$update_spacecraft->picture))) 
            {
                Storage::delete('public/'.$update_spacecraft->picture);
            }

            $file = $request->file('picture')->store('picture', 'public');
            $update_spacecraft->picture = $file;
        }

        $update_spacecraft->save();
        return redirect()->route('skyobject.edit',['skyobject'=>$update_spacecraft])->with('status', 'Sky Object Data was Updated Successfully');
    }

    public function destroy($id)
    {
        $skyobject = SkyObject::findOrFail($id);
        if ($skyobject->picture && file_exists(storage_path('app/public/'.$skyobject->picture))) 
        {
            Storage::delete('public/'.$skyobject->picture);
        }
        $skyobject->delete();
        return redirect()->back()->with('status', 'Sky Object was Successfully deleted');
    }

    public function search(Request $request)
    {
       $cari = $request->get('search');
       $skyobject = SkyObject::where('name', 'LIKE', '%'.$cari.'%')->orderBy('created_at', 'DESC')->paginate(5);
       return view('skyobject.index', ['skyobject'=>$skyobject]);
    }
}

resources/views/skyobject/create.blade.php
@extends('templates.home')
@section('title')
    Create Sky Object Data
@endsection
@section('content')
    <div class="container" >
        <h3>Input Sky Object Data</h3>
        <hr>
        @if (session('status'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{ session('status') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
        @endif
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5> Input Sky Object Data</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('skyobject.store') }}" class="form-group" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="name" >Sky Object Name</label>
                            </div>
                            <div class="col-md-8">
                                <input value="{{ old('name') }}" type="text" class="form-control {{$errors->first('name') ? "is-invalid": ""}}" name="name" id="name">
                                    <div class="invalid-feedback"> 
                                        {{$errors->first('name')}}
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="type" >Type</label>
                            </div>
                            <div class="col-md-8">
                                <input value="{{ old('type') }}" type="text" class="form-control {{$errors->first('type') ? "is-invalid": ""}}" name="type" id="type">
                                    <div class="invalid-feedback"> 
                                        {{$errors->first('type')}}
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="distance">Distance</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control {{$errors->first('distance') ? "is-invalid": ""}}" name="distance" id="distance">
                                    <div class="invalid-feedback">
                                        {{$errors->first('distance')}}
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                Picture
                            </div>
                            <div class="col-md-8">
                                <div class="custom-file">
                                    <label for="picture" class="custom-file-label">Picture</label>
                                        <input type="file" class="custom-file-input {{$errors->first('picture') ? "is-invalid": ""}}" name="picture" id="picture">
                                            <div class="invalid-feedback">
                                                {{$errors->first('picture')}}
                                            </div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary">Create</button>
                            </div>
                        </div>
                    </form>   
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/skyobject/edit.blade.php
@extends('templates.home')
@section('title')
    Edit Sky Object
@endsection
@section('content')
    <div class="container" >
        <h3>Edit Sky Object</h3>
        <hr>
        @if (session('status'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{ session('status') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
        @endif
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5>Edit Sky Object Data</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('skyobject.update',$skyobject['id']) }}" method="POST" class="form-group" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-3">
                                <label for="name" class="text-primary">Sky Object Name</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control {{$errors->first('name') ? "is-invalid": ""}}" name="name" id="name" 
                                value="{{ old('name') ? old('name') : $skyobject['name'] }}">
                                    <div class="invalid-feedback">
                                        {{$errors->first('name')}}
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="type" class="text-primary">Type</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control {{$errors->first('type') ? "is-invalid": ""}}" name="type" id="type" 
                                value="{{ old('type') ? old('type') : $skyobject['type'] }}">
                                    <div class="invalid-feedback">
                                        {{$errors->first('type')}}
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                                <div class="col-md-3">
                                    <label for="distance" class="text-primary">Distance</label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" class="form-control {{$errors->first('distance') ? "is-invalid": ""}}" name="distance" id="distance" 
                                    value="{{ old('distance') ? old('distance') : $skyobject['distance'] }}">
                                        <div class="invalid-feedback">
                                            {{$errors->first('distance')}}
                                        </div>
                                </div>
                            </div>
                            <br>
                        <div class="row">
                            <div class="col-md-3">
                                Picture
                            </div>
                        <div class="col-md-8">
                                <img src="{{asset('storage/'.$skyobject['picture'])}}" class="img-thumbnail" height="150px" width="150px" alt="">
                                    <div class="custom-file">
                                        <label for="picture" class="custom-file-label">Picture</label>
                                            <input type="file" class="custom-file-input {{$errors->first('picture') ? "is-invalid": ""}}" name="picture" id="picture">
                                                <div class="invalid-feedback">
                                                    {{$errors->first('picture')}}
                                                </div>
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary" >Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/skyobject/index.blade.php
@extends('templates.home')
@section('title')
    Sky Object Index 
@endsection
@section('css')
<style>
	body{
		padding-top: 30px;
	}
	th, td {
		padding: 10px;
		text-align: center;
	}
	td a{
		margin: 3px;
		align-content: center;
		color: white;
	}
	td a:hover{
		text-decoration: none;
	}
	td button{
		margin-top: 5px;
		cursor: pointer;
	 }
</style>
@endsection
@section('content')
	<div class="container">
		<h3> Sky Object Index</h3>
		<hr>
		@if (session('status'))
		<div class="alert alert-info alert-dismissible fade show" role="alert">
			<strong> {{ session('status') }} </strong>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		@endif
		<div class="row">
			<div class="col-md-2">
				<a href=" {{ route('skyobject.create') }} " class="btn btn-outline-primary">
					<span data-feather="plus-square"></span> Add Sky Object<span class="sr-only">(current)</span>
				</a>
			</div>
			<div class="col-md-8">
				<form action=" {{ route('skyobject.search') }} " method="get">
					<div class="input-group custom-search-form">
						<input type="text" name="search" placeholder="Filter by Name" class="form-control">
						<span class="input-group-btn">&nbsp;
							<button class="btn btn-outline-dark" type="submit">Filter</button>
						</span>
					</div>
				</form>
			</div>
		</div>
		<br>
		<div class="tabel-responsive">
			<table class="table table-hover">
				<thead>
					<tr class="table-primary">
						<th scope="col">ID</th>
						<th scope="col">Name</th>
                        <th scope="col">Type</th>
						<th scope="col">Picture</th>
						<th scope="col">Action</th>
					</tr>
				</thead>
				<tbody>
				@foreach ($skyobject as $skyobjects)
					<tr>
						<th>{{ $skyobjects['id'] }}</th>
                        <th>{{ $skyobjects['name'] }}</th>
                        <th>{{ $skyobjects['type'] }}</th>
						<td>
							<img src="{{asset('storage/'.$skyobjects['picture'])}}" class="img-thumbnail" width="80px" alt="">
						</td>
						<td>
							
							<a href="{{ route('skyobject.show', ['id'=>$skyobjects['id']]) }}" class="btn-sm btn-primary">
								<span data-feather="eye"></span> Detail<span class="sr-only">(current)</span>
							</a>
							<a href="{{ route('skyobject.edit', ['id'=>$skyobjects['id']]) }}" class="btn-sm btn-success">
								<span data-feather="edit"></span> Edit<span class="sr-only">(current)</span>
							</a>
							<form class="d-inline" onsubmit="return confirm('Permanently Delete Sky Object?')" action="{{ route('skyobject.destroy', ['id'=>$skyobjects['id']]) }}" method="POST">
								@csrf
								@method('DELETE')
								<button type="submit" class="btn-sm btn-danger" value="Delete" name="submit">
									<span data-feather="trash"></span> Delete<span class="sr-only">(current)</span>
								</button>
							</form>
						</td>
					</tr>
				@endforeach
				</tbody>
			</table>
		</div>
		<div class="pagination justify-content-center"> {{ $skyobject->links() }} </div>
	</div>
@endsection

resources/views/skyobject/show.blade.php
@extends('templates.home')
@section('title')
    Detail Sky Object
@endsection
@section('content')
    <h1>Detail Sky Object </h1>
    <hr>
    <br>
    <div class="card bg-white border-info" style="max-width: 70%; margin: auto; min-height: 400px;">
			<div class="row" style="padding: 25px;">
				<div class="col-md-6 offset-sm-2 offset-md-3 ">
					<img src="{{asset('storage/'.$skyobject['picture'])}}" class="img-thumbnail" width="300px" alt="">
				</div>
            </div>
            
			<div class="row">
				<div class="col-md-12 text-center">
					<h3>{{ $skyobject['name'] }} </h3>
				</div>
			</div>
            <hr>
            
			<br>
			
			<div class="row">
				<div class="col-md-3 offset-md-2 col-sm-3 offset-sm-2">
					<b>Type</b>
				</div>
				<br>
			</div>
				<div class="col-md-5 col-sm-4">
					{{ $skyobject['type'] }}
				</div>

			<div class="row">
				<div class="col-md-3 offset-md-2 col-sm-3 offset-sm-2">
					<b>Distance</b>
				</div>
				<div class="col-md-4 col-sm-4">
					{{ $skyobject['distance'] }}
				</div>
				<br>
			</div>
    </div>
@endsection