routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');


Route::resource('user', 'UserController');
Route::get('/user', 'UserController@search')->name('user.search');

Route::resource('post', 'PostController');
Route::get('/post', 'PostController@search')->name('post.search');

Route::resource('skyobject', 'SkyObjectController');
Route::get('/skyobject', 'SkyObjectController@search')->name('skyobject.search');

Route::resource('spacecraft', 'SpacecraftController');
Route::get('/spacecraft', 'SpacecraftController@search')->name('spacecraft.search');

Route::resource('occurrence', 'OccurrenceController');
Route::get('/occurrence', 'OccurrenceController@search')->name('occurrence.search');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Occurrence.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Occurrence extends Model
{
    public $table = 'occurrence';
    protected $fillable = [
        'name', 'date','description',
    ];
}

app/Http/Controllers/OccurrenceController.php
<?php

namespace App\Http\Controllers;
use App\Occurrence;
use Illuminate\Http\Request;

class OccurrenceController extends Controller
{
    public function index()
    {
        $occurrence = \App\Occurrence::paginate();
        return view('occurrence.index',compact('occurrence'));
    }

    public function create()
    {
        $occurrence = Occurrence::all();
        return view('occurrence.create', ['occurrence'=>$occurrence]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'date'=>'required|date',
            'description'=>'required',
            'picture'=>'required|image|mimes:jpg,jpeg,png,bmp',
        ]);

        $file = $request->file('picture');
        $path = $file->store('picture', 'public');

        Occurrence::create([
            'name'=>$request->name,
            'date'=>$request->date,
            'description'=>$request->description,
            'picture'=>$path,
        ]);

        return redirect()->route('occurrence.create')->with('status', 'Sky Event Data was Successfully Created');
    }

    public function show($id)
    {
        $occurrence = Occurrence::findOrFail($id);
        return view('occurrence.show',['occurrence'=>$occurrence]);
    }

    public function edit($id)
    {
        $occurrence = Occurrence::findOrFail($id);
        return view('occurrence.edit',['occurrence'=>$occurrence]);
    }

    public function update(Request $request, $id)
    {
        $update_spacecraft = Occurrence::findOrFail($id);
        $request->validate([
            'name'=>'required',
            'date'=>'required|date',
            'description'=>'required',
            'picture'=>'required|image|mimes:jpg,jpeg,png,bmp',
        ]);

        $update_spacecraft->update([
            'name'=>$request->name,
            'date'=>$request->date,
            'description'=>$request->description,
            'picture'=>$request->picture,
        ]);

        if($request->file('picture')) 
        {
            if ($update_spacecraft->picture && file_exists(storage_path('app/public/'.$update_spacecraft->picture))) 
            {
                Storage::delete('public/'.$update_spacecraft->picture);
            }

            $file = $request->file('picture')->store('picture', 'public');
            $update_spacecraft->picture = $file;
        }

        $update_spacecraft->save();
        return redirect()->route('occurrence.edit',['occurrence'=>$update_spacecraft])->with('status', 'Sky Event Data was Updated Successfully');
    }

    public function destroy($id)
    {
        $occurrence = Occurrence::findOrFail($id);
        if ($occurrence->picture && file_exists(storage_path('app/public/'.$occurrence->picture))) 
        {
            Storage::delete('public/'.$occurrence->picture);
        }
        $occurrence->delete();
        return redirect()->back()->with('status', 'Sky Event was Successfully deleted');
    }

    public function search(Request $request)
    {
       $cari = $request->get('search');
       $occurrence = Occurrence::where('name', 'LIKE', '%'.$cari.'%')->orderBy('created_at', 'DESC')->paginate(5);
       return view('occurrence.index', ['occurrence'=>$occurrence]);
    }
}

resources/views/occurrence/create.blade.php
@extends('templates.home')
@section('title')
    Create Sky Event Data
@endsection
@section('content')
    <div class="container" >
        <h3>Input Sky Event Data</h3>
        <hr>
        @if (session('status'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{ session('status') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
        @endif
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5> Input Sky Event Data</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('occurrence.store') }}" class="form-group" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="name" >Sky Event Name</label>
                            </div>
                            <div class="col-md-8">
                                <input value="{{ old('name') }}" type="text" class="form-control {{$errors->first('name') ? "is-invalid": ""}}" name="name" id="name">
                                    <div class="invalid-feedback"> 
                                        {{$errors->first('name')}}
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="date" >Date</label>
                            </div>
                            <div class="col-md-8">
                                <input value="{{ old('date') }}" type="date" class="form-control {{$errors->first('date') ? "is-invalid": ""}}" name="date" id="date">
                                    <div class="invalid-feedback"> 
                                        {{$errors->first('date')}}
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="description">Description</label>
                            </div>
                            <div class="col-md-8">
                                <textarea class="form-control {{$errors->first('description')? "is-invalid": ""}}" name="description" id="description" cols="30" rows="5"></textarea>
                                <div class="invalid-feedback">
                                    {{$errors->first('description')}}
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                Picture
                            </div>
                            <div class="col-md-8">
                                <div class="custom-file">
                                    <label for="picture" class="custom-file-label">Picture</label>
                                        <input type="file" class="custom-file-input {{$errors->first('picture') ? "is-invalid": ""}}" name="picture" id="picture">
                                            <div class="invalid-feedback">
                                                {{$errors->first('picture')}}
                                            </div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary">Create</button>
                            </div>
                        </div>
                    </form>   
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/occurrence/edit.blade.php
@extends('templates.home')
@section('title')
    Edit Sky Event Data
@endsection
@section('content')
    <div class="container" >
        <h3>Edit Sky Event Data</h3>
        <hr>
        @if (session('status'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{ session('status') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
        @endif
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5>Edit Sky Event Data</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('occurrence.update',$occurrence['id']) }}" method="POST" class="form-group" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-3">
                                <label for="name" class="text-primary">Sky Event Name</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control {{$errors->first('name') ? "is-invalid": ""}}" name="name" id="name" 
                                value="{{ old('name') ? old('name') : $occurrence['name'] }}">
                                    <div class="invalid-feedback">
                                        {{$errors->first('name')}}
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="date" class="text-primary">Date</label>
                            </div>
                            <div class="col-md-8">
                                <input type="date" class="form-control {{$errors->first('date') ? "is-invalid": ""}}" name="date" id="date" 
                                value="{{ old('date') ? old('date') : $occurrence['date'] }}">
                                    <div class="invalid-feedback">
                                        {{$errors->first('date')}}
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="description" class="text-primary">Description</label>
                            </div>
                            <div class="col-md-8">
                                <textarea class="form-control {{$errors->first('description') ? "is-invalid": ""}}" 
                                    name="description" id="description" value="{{ old('description') ? old('description') : $occurrence['description'] }}"></textarea>
                                    <div class="invalid-feedback">
                                        {{$errors->first('description')}}
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                Picture
                            </div>
                        <div class="col-md-8">
                                <img src="{{asset('storage/'.$occurrence['picture'])}}" class="img-thumbnail" height="150px" width="150px" alt="">
                                    <div class="custom-file">
                                        <label for="picture" class="custom-file-label">Picture</label>
                                            <input type="file" class="custom-file-input {{$errors->first('picture') ? "is-invalid": ""}}" name="picture" id="picture">
                                                <div class="invalid-feedback">
                                                    {{$errors->first('picture')}}
                                                </div>
                                    </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary" >Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/occurrence/index.blade.php
@extends('templates.home')
@section('title')
 	Index Post
@endsection
@section('css')
<style>
	body{
		padding-top: 30px;
	}
	th, td {
		padding: 10px;
		text-align: center;
	}
	td a{
		margin: 3px;
		align-content: center;
		color: white;
	}
	td a:hover{
		text-decoration: none;
	}
	td button{
		margin-top: 5px;
		cursor: pointer;
	 }
</style>
@endsection
@section('content')
	<div class="container">
		<h3> Post Index</h3>
		<hr>
		@if (session('status'))
		<div class="alert alert-info alert-dismissible fade show" role="alert">
			<strong> {{ session('status') }} </strong>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		@endif
		<div class="row">
			<div class="col-md-2">
				<a href=" {{ route('occurrence.create') }} " class="btn btn-outline-primary">
					<span data-feather="plus-square"></span> Add Sky Event<span class="sr-only">(current)</span>
				</a>
			</div>
			<div class="col-md-8">
				<form action=" {{ route('occurrence.search') }} " method="get">
					<div class="input-group custom-search-form">
						<input type="text" name="search" placeholder="Filter by Name" class="form-control">
						<span class="input-group-btn">&nbsp;
							<button class="btn btn-outline-dark" type="submit">Filter</button>
						</span>
					</div>
				</form>
			</div>
		</div>
		<br>
		<div class="tabel-responsive">
			<table class="table table-hover">
				<thead>
					<tr class="table-primary">
						<th scope="col">ID</th>
						<th scope="col">Name</th>
                        <th scope="col">Date</th>
						<th scope="col">Picture</th>
						<th scope="col">Action</th>
					</tr>
				</thead>
				<tbody>
				@foreach ($occurrence as $happen)
					<tr>
						<th>{{ $happen['id'] }}</th>
                        <th>{{ $happen['name'] }}</th>
                        <th>{{ $happen['date'] }}</th>
						<td>
							<img src="{{ asset('storage/'.$happen['picture']) }}" alt="N/A" width="80px">
						</td>
						<td>
							
							<a href="{{ route('occurrence.show', ['id'=>$happen['id']]) }}" class="btn-sm btn-primary">
								<span data-feather="eye"></span> Detail<span class="sr-only">(current)</span>
							</a>
							<a href="{{ route('occurrence.edit', ['id'=>$happen['id']]) }}" class="btn-sm btn-success">
								<span data-feather="edit"></span> Edit<span class="sr-only">(current)</span>
							</a>
							<form class="d-inline" onsubmit="return confirm('Permanently Delete This Sky Event?')" action="{{ route('occurrence.destroy', ['id'=>$happen['id']]) }}" method="POST">
								@csrf
								@method('DELETE')
								<button type="submit" class="btn-sm btn-danger" value="Delete" name="submit">
									<span data-feather="trash"></span> Delete<span class="sr-only">(current)</span>
								</button>
							</form>
						</td>
					</tr>
				@endforeach
				</tbody>
			</table>
		</div>
		<div class="pagination justify-content-center"> {{ $occurrence->links() }} </div>
	</div>
@endsection

resources/views/occurrence/show.blade.php
@extends('templates.home')
@section('title')
    Detail Sky Event
@endsection
@section('content')
    <h1>Detail Sky Event </h1>
    <hr>
    <br>
    <div class="card bg-white border-info" style="max-width: 70%; margin: auto; min-height: 400px;">
			<div class="row" style="padding: 25px;">
				<div class="col-md-6 offset-sm-2 offset-md-3 ">
					<img src="{{asset('storage/'.$occurrence['picture'])}}" class="img-thumbnail" width="300px" alt="">
				</div>
            </div>
            
			<div class="row">
				<div class="col-md-12 text-center">
					<h3>{{ $occurrence['name'] }} </h3>
				</div>
			</div>
            <hr>
            
			<br>

			<div class="row">
				<div class="col-md-3 offset-md-2 col-sm-3 offset-sm-2">
					<b>Date</b>
				</div>
				<div class="col-md-4 col-sm-4">
					{{ $occurrence['date'] }}
				</div>
				<br>
			</div>

			<div class="row">
				<div class="col-md-3 offset-md-2 col-sm-3 offset-sm-2">
					<b>Description</b>
				</div>
				<div class="col-md-4 col-sm-4">
					{{ $occurrence['description'] }}
				</div>
				<br>
			</div>
    </div>
@endsection